### ISSUE TITLE
About the baseline (GA-D) in your paper.

### ISSUE THREAD

**Issue by jkwang93** [yutxie/MARS#2]
Hello, great job. I also saw another article on this year's ICLR, which is similar to your work, but the results of the GA-D model in the baseline are quite different from yours. And I also used the default model of GA-D to run the task of jnk+gsk+sa+qed, but I couldn’t get the molecules that meet the 4 conditions. Could you please show me the code of the GA-D in your baseline?

**Comment by yutxie** [comment]
Hi, thanks for your interest to our work! 

We implemented the GA-D baseline based on [their official code repository](https://github.com/aspuru-guzik-group/GA) with some subtle modification on the [fitness computation function](https://github.com/aspuru-guzik-group/GA/blob/master/generation_props.py).  We're sorry that our modified code of GA-D was missing due to server maintenance. The differences of GA-D experiment results might come from the unstable characteristics of both the GA and the discriminator. In our paper, we reported the best performance that GA-D can achieve.

Hope this could help!
